production:
    username: cdkbot
    uuid: cdkbot
    apikey: $SQA_API_KEY
    token: $SQA_API_KEY
    env_name: production
    weebl_url: http://10.131.231.53:8080
    jenkins_url: http://10.131.231.80:8080
    smtp_from: noreply@canonical.com
    smtp_pass: figandleaves
    smtp_port: 465
    smtp_server: smtp.canonical.com
    smtp_user: canonical

