name: Rebuild Release Branch

on:
  workflow_dispatch:
    inputs:
      branches:
        type: string
        required: false
        default: ""  # defaults to all branches
        description: |-
          Run on which k8s-snap branches.
          list all branches necessary by spaces.
          If empty, it will evaluate on all branches
      dry_run:
        type: boolean
        required: false
        default: false
        description: |-
          If true, it will not trigger the builds, just print which would be built
  schedule:
    - cron: '0 0 * * 0'  # Runs weekly on Sunday

permissions:
  contents: read

jobs:
  release-track:
    runs-on: ubuntu-latest
    env:
      LPCREDS_B64: ${{ secrets.LP_CREDS }}
    steps:
      - name: Checking out repo
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
      - run: pip install -r scripts/requirements.txt
      - run: 'echo $LPCREDS_B64 | base64 --decode > lp_creds'
      - name: Rebuild Branches
        run: |
          LPCREDS=./lp_creds scripts/request_builds.py --branch ${{ inputs.branches }}${{ inputs.dry_run && ' --dry-run' || '' }}
